// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSNEu4iIdgQVCGV2xYiHxWtVh_oEcYUTA',
    appId: '1:701364834705:web:f1c7cd9b11ef3807f4ca30',
    messagingSenderId: '701364834705',
    projectId: 'notify-master-88af3',
    authDomain: 'notify-master-88af3.firebaseapp.com',
    databaseURL: 'https://notify-master-88af3.firebaseio.com',
    storageBucket: 'notify-master-88af3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXZxt9PlFx6bf8MOBbTUzwsbyr7PbdcO0',
    appId: '1:701364834705:android:8ccc57207cdc8d8bf4ca30',
    messagingSenderId: '701364834705',
    projectId: 'notify-master-88af3',
    databaseURL: 'https://notify-master-88af3.firebaseio.com',
    storageBucket: 'notify-master-88af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3CPctOpUQHdc3zcrPLi60EF3eugwwT0',
    appId: '1:701364834705:ios:064d73d80d916709f4ca30',
    messagingSenderId: '701364834705',
    projectId: 'notify-master-88af3',
    databaseURL: 'https://notify-master-88af3.firebaseio.com',
    storageBucket: 'notify-master-88af3.appspot.com',
    androidClientId: '701364834705-4ap3vgh63jd656hslo2oltt98tlb4o3s.apps.googleusercontent.com',
    iosBundleId: 'com.ztech.mobilebanking.mobileBankingFlutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk3CPctOpUQHdc3zcrPLi60EF3eugwwT0',
    appId: '1:701364834705:ios:064d73d80d916709f4ca30',
    messagingSenderId: '701364834705',
    projectId: 'notify-master-88af3',
    databaseURL: 'https://notify-master-88af3.firebaseio.com',
    storageBucket: 'notify-master-88af3.appspot.com',
    androidClientId: '701364834705-4ap3vgh63jd656hslo2oltt98tlb4o3s.apps.googleusercontent.com',
    iosBundleId: 'com.ztech.mobilebanking.mobileBankingFlutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSNEu4iIdgQVCGV2xYiHxWtVh_oEcYUTA',
    appId: '1:701364834705:web:1e265c736fc12b73f4ca30',
    messagingSenderId: '701364834705',
    projectId: 'notify-master-88af3',
    authDomain: 'notify-master-88af3.firebaseapp.com',
    databaseURL: 'https://notify-master-88af3.firebaseio.com',
    storageBucket: 'notify-master-88af3.appspot.com',
  );
}
